services:
  - type: web
    name: dilys-kitchen
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn delices_backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: django-insecure-delices-de-marie-secret-key-change-in-production-123456789
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: dilys-kitchen.onrender.com
